# Generated by Django 5.0.1 on 2024-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Avatar Image')),
                ('mobile_number', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('person_name', models.CharField(max_length=50, verbose_name='person Name')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'ContactBook',
                'verbose_name_plural': 'ContactBooks',
            },
        ),
    ]
